### ISSUE TITLE
support uglify-js 2.x.x

### ISSUE THREAD

**Issue by ruffle1986** [klesh/density-trie#1]
Hi,

first of all, let me say thank you for all of this what you've done here. It's great!

We, at Intellyo, use your module to measure keyword density within a text, but we would like to minify our code via Uglify js 2.x.x which doesn't support the `for .. of` syntax. 

Would you mind if we open a pull request where we change `for .. of` to `forEach` or something that is supported by Uglify js?

Thank you in advance!

**Comment by klesh** [comment]
Great work, thanks for your contribution.

**Comment by ruffle1986** [comment]
Thanks for your quick response! Awesome!

**Comment by ruffle1986** [comment]
https://github.com/klesh/density-trie/pull/2
